config/routes.rb
Rails.application.routes.draw do
  resources :populations
  root :to => 'populations#index', :as => 'home'
  match '/populations/validate/', :to => 'populations#validate', :as => 'populations_validate', :via => [:get, :post]

end

app/models/population.rb
class Population < ActiveRecord::Base
  validates_presence_of :zone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController
  require 'open-uri'
  include PopulationsHelper
  before_action :set_population, only: [:show, :edit, :update, :destroy]

  # GET /populations
  # GET /populations.json
  def index
    data = get_data
    @populations = get_populations data["data"]["table-data"]["values"]

    #for create population
    @population = Population.new
    @images = data["data"]["carousel"]["images"]
    @about = data["data"]["table-data"]["about"]
    @source = data["data"]["table-data"]["source"]
  end

  def validate
    @population = nil
    @saved = false
    if params["population"]
      @population =  Population.new(population_params)
      @population.updated_at = @population.created_at = DateTime.now
      if @population.valid?
        @saved = @population.save
        data = get_data
        @populations = get_populations data["data"]["table-data"]["values"]

        #if population save i need send empty population to form
        @population = Population.new if @saved

      end
    end
  end


  # GET /populations/1
  # GET /populations/1.json
  def show
  end

  # GET /populations/new
  def new
    @population = Population.new(population_params)
  end

  # GET /populations/1/edit
  def edit
  end

  # POST /populations
  # POST /populations.json
  def create
    @population = Population.new(population_params)

    respond_to do |format|
      if @population.save
        format.html { redirect_to @population, notice: 'Population was successfully created.' }
        format.json { render :show, status: :created, location: @population }
      else
        format.html { render :new }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /populations/1
  # PATCH/PUT /populations/1.json
  def update
    respond_to do |format|
      if @population.update(population_params)
        format.html { redirect_to @population, notice: 'Population was successfully updated.' }
        format.json { render :show, status: :ok, location: @population }
      else
        format.html { render :edit }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /populations/1
  # DELETE /populations/1.json
  def destroy
    @population.destroy
    respond_to do |format|
      format.html { redirect_to populations_url, notice: 'Population was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_population
      @population = Population.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def population_params
      params.require(:population).permit(:zone, :y1993, :y2005, :y2010, :y2015)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/populations_helper.rb
module PopulationsHelper
  #consuming api service
  def get_data
    JSON.load(open("http://aspirantes.hablacreativo.com/api/v1/admission_test"))
  end

  def get_populations_api values
    populations = []
    values.each { |value| populations << Population.new(value) }
    populations
  end

  def get_populations values
    populations = Population.all
    populations += get_populations_api values
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HablaCreativo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://blackrockdigital.github.io/startbootstrap-full-slider/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://blackrockdigital.github.io/startbootstrap-half-slider/css/half-slider.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="https://blackrockdigital.github.io/startbootstrap-freelancer/css/freelancer.min.css" rel="stylesheet">
  <link href="https://blackrockdigital.github.io/startbootstrap-freelancer/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation -->

<%= yield %>

</body>
</html>

app/views/populations/_carousel.html.erb
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @images.each_with_index do |image, index| %>
        <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
    <% end %>

  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <% @images.each_with_index do |image, index| %>
        <div class="item <%= 'active' if index == 0 %>">
          <% o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
             string = (0...50).map { o[rand(o.length)] }.join %>
          <!-- Set the second background image using inline CSS below. -->
          <div class="fill" style="background-image:url('<%= image + "?#{string}" %>');background-size: 640px 480px;background-repeat: no-repeat;">
          </div>
          <div class="carousel-caption">
          </div>
        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>

</header>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    });
</script>

app/views/populations/_form.html.erb
<div class="container">
  <%= form_for(@population) do |f| %>
      <% if @population.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@population.errors.count, "error") %> prohibited this population from being saved:</h2>

            <ul>
              <% @population.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div id="attributes" <% unless @population.errors.any? %> style="display: none;" <% end %> >
        <div class="form-group">
          <%= f.label :zone, :for => 'population_zone' %> <span class="required">*</span>
          <%= f.text_field :zone, :class => 'form-control' %>
          <small class="required"><%= I18n.t(:field_required) %></small>
        </div>

        <div class="form-group">
          <%= f.label :y1993, :for => 'population_y1993' %>
          <%= f.number_field :y1993, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :y2005, :for => 'population_y2005' %>
          <%= f.number_field :y2005, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :y2010, :for => 'population_y2010' %>
          <%= f.number_field :y2010, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :y2015, :for => 'population_y2015' %>
          <%= f.number_field :y2015, :class => 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit :class => 'btn btn-primary', :onclick => "validate_form( '#{escape_javascript populations_validate_path(:format => 'js')}' ); return false" %>
          <%= f.button  I18n.t(:label_cancel), :class => 'btn btn-primary', :onclick => 'return show_form()'  %>
        </div>

      </div>


      <div class="actions" id="show-button" <% if @population.errors.any? %> style="display: none;" <% end %>>
        <%= f.button :class => 'btn btn-primary', :onclick => 'return show_form()' %>
      </div>
  <% end %>
</div>

app/views/populations/_highchart.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<div id="container-chart" style="width: 100%; margin: 0 auto"></div>

<script type="text/javascript" charset="utf-8">
    Highcharts.chart('container-chart', {
        title: {
            text: ''
        },
        xAxis: {
            categories: ['1993', '2005', '2010', '2015'],
            title: {
                enabled: false
            }
        },
        yAxis: {
            title: {
                text: '<%= I18n.t(:field_population) %>'
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle'
        },

        series: [
            <% @populations.each do |population| %>
            {
                name: '<%= population.zone ? population.zone : 'Unnamed Zone' %>',
                data: [<%= population.y1993 ? population.y1993 : 0 %>, <%=  population.y2005 ? population.y2005 : 0  %>, <%= population.y2010 ? population.y2010 : 0 %>, <%= population.y2015 ? population.y2015 : 0 %>]
            },
            <% end %>
        ]

    });

</script>

app/views/populations/_list.html.erb
<div class="container" id="table-population">
  <div id="form-container">
    <%= render partial: 'form' %>
  </div>
  <table id="example" class="display table" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th><%= I18n.t(:field_zone) %></th>
      <th><%= I18n.t(:field_y1993) %></th>
      <th><%= I18n.t(:field_y2005) %></th>
      <th><%= I18n.t(:field_y2010) %></th>
      <th><%= I18n.t(:field_y2015) %></th>
      <th><%= I18n.t(:field_created_at) %></th>
      <th><%= I18n.t(:field_updated_at) %></th>
    </tr>
    </thead>
    <tfoot>
    <tr>
      <th><%= I18n.t(:field_zone) %></th>
      <th><%= I18n.t(:field_y1993) %></th>
      <th><%= I18n.t(:field_y2005) %></th>
      <th><%= I18n.t(:field_y2010) %></th>
      <th><%= I18n.t(:field_y2015) %></th>
      <th><%= I18n.t(:field_created_at) %></th>
      <th><%= I18n.t(:field_updated_at) %></th>
    </tr>
    </tfoot>
    <tbody>
    <% @populations.each do |population| %>
        <tr>
          <td><%= population.zone %></td>
          <td><%= population.y1993 %></td>
          <td><%= population.y2005 %></td>
          <td><%= population.y2010 %></td>
          <td><%= population.y2015 %></td>
          <td><%= population.created_at.to_s %></td>
          <td><%= population.updated_at.to_s %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#example').DataTable();
    });
</script>

app/views/populations/edit.html.erb
<h1>Editing Population</h1>

<%= render 'form' %>

<%= link_to 'Show', @population %> |
<%= link_to 'Back', populations_path %>

app/views/populations/index.html.erb
<!-- jQuery -->
<script src="https://blackrockdigital.github.io/startbootstrap-full-slider/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://blackrockdigital.github.io/startbootstrap-full-slider/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="https://blackrockdigital.github.io/startbootstrap-freelancer/js/freelancer.min.js"></script>

<header>
  <div class="container" style="padding-top: 50px !important">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-text">
          <span class="name"><%= @about %></span>
          <hr class="star-light">
          <div id="highchart-container">
            <%= render partial: 'highchart' %>
          </div>
          <a style="color: #ffffff !important" target="_blank" href="<%= @source %>" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
        </div>
      </div>
    </div>
  </div>
</header>

<hr>

<div id="list-container">
  <%= render partial: 'list' %>
</div>

<hr>

<!-- Full Page Image Background Carousel Header -->
<%= render partial: 'carousel' %>

app/views/populations/new.html.erb
<h1>New Population</h1>

<%= render 'form' %>

<%= link_to 'Back', populations_path %>

app/views/populations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zone:</strong>
  <%= @population.zone %>
</p>

<p>
  <strong>Y1993:</strong>
  <%= @population.y1993 %>
</p>

<p>
  <strong>Y2005:</strong>
  <%= @population.y2005 %>
</p>

<p>
  <strong>Y2010:</strong>
  <%= @population.y2010 %>
</p>

<p>
  <strong>Y2015:</strong>
  <%= @population.y2015 %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @population.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @population.updated_at %>
</p>

<%= link_to 'Edit', edit_population_path(@population) %> |
<%= link_to 'Back', populations_path %>

app/views/populations/validate.js.erb
<% if @saved %>
$('div#list-container').empty();
$('div#list-container').append('<%= escape_javascript(render :partial => 'list') %>');
if($("#container-chart").highcharts()) $("#container-chart").highcharts().destroy();
$('div#highchart-container').empty();
$('div#highchart-container').append('<%= escape_javascript(render :partial => 'highchart') %>');
<% else %>
$('div#form-container').empty();
$('div#form-container').append('<%= escape_javascript(render :partial => 'form') %>');
<% end %>